name: Test Javadoc

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build Javadoc
        run: ./gradlew build javadoc
        shell: bash
